# Generated by Django 2.2.4 on 2020-07-02 22:59

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ModalityCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'modalidad de cursada',
                'verbose_name_plural': 'modalidades de cursada',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre y Apellido')),
                ('profession', models.CharField(blank=True, max_length=300, null=True, verbose_name='Profesión')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='professor', verbose_name='Foto')),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografia')),
                ('dni', models.IntegerField(blank=True, null=True, verbose_name='DNI')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('cellPhone', models.TextField(blank='True', null=True, verbose_name='Celular')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('acronym', models.CharField(blank=True, max_length=20, null=True, verbose_name='Acrónimo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university', verbose_name='Logo')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'universidad',
                'verbose_name_plural': 'universidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('objective', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Objetivo')),
                ('program', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Programa')),
                ('imageCourse', models.ImageField(blank=True, null=True, upload_to='imageCourses', verbose_name='Imagen del Curso')),
                ('url', models.URLField(blank=True, null=True)),
                ('dollarPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio en dolares')),
                ('pesoPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio en pesos')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('published', models.DateTimeField(default=datetime.datetime(2020, 7, 2, 22, 59, 50, 471144, tzinfo=utc), verbose_name='Fecha de Publicación')),
                ('categories', models.ManyToManyField(related_name='get_categories', to='courses.Category', verbose_name='Categorias')),
                ('modality', models.ManyToManyField(related_name='get_modalities', to='courses.ModalityCourse', verbose_name='Modalidad')),
                ('professor', models.ManyToManyField(related_name='get_professors', to='courses.Professor', verbose_name='Profesor')),
                ('tags', models.ManyToManyField(related_name='get_tags', to='courses.Tag', verbose_name='Tags')),
                ('university', models.ManyToManyField(related_name='get_course_universitys', to='courses.University', verbose_name='Universidad')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'ordering': ['order', 'title'],
            },
        ),
    ]
