# Generated by Django 2.2.4 on 2020-07-05 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hoursDuration',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Horas de Duración del curso'),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 55, 29, 428462, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
