# Generated by Django 2.2.4 on 2020-07-07 00:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200704_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='urlMercadoPago',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='urlPayPaL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 0, 1, 51, 309241, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
