# Generated by Django 2.2.4 on 2020-07-07 00:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200706_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 7, 0, 13, 42, 391891, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin'),
        ),
    ]
