# Generated by Django 2.0.2 on 2020-08-13 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200813_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 17, 52, 32, 638625, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
