# Generated by Django 2.0.2 on 2020-08-25 00:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200813_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 0, 2, 2, 491177, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
