# Generated by Django 2.0.2 on 2020-08-25 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200825_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 25, 0, 23, 45, 513576, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
