# Generated by Django 2.0.2 on 2021-06-11 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200825_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 16, 16, 24, 316351, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
