# Generated by Django 2.2.4 on 2021-07-24 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20210611_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 0, 18, 22, 392837, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
