# Generated by Django 4.0.6 on 2023-07-01 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210723_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 1, 17, 56, 16, 763074, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
