# Generated by Django 4.0.6 on 2023-12-26 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 26, 18, 33, 23, 370807, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='course',
            name='urlPayPaL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
