# Generated by Django 4.0.6 on 2023-12-27 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_course_published_alter_course_urlpaypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 13, 21, 35, 60432, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
