# Generated by Django 4.0.6 on 2023-12-28 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 28, 17, 2, 24, 319714, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
