# Generated by Django 4.0.6 on 2024-02-18 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 52, 45, 243729, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
