# Generated by Django 4.0.6 on 2024-02-18 21:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 56, 33, 25103, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='course',
            name='urlMercadoPago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
