# Generated by Django 4.0.6 on 2024-02-18 21:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_course_published_alter_course_urlmercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='idUrlMercadoPago',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 21, 59, 59, 583014, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='course',
            name='urlMercadoPago',
            field=models.URLField(blank=True, null=True),
        ),
    ]
