# Generated by Django 4.0.6 on 2024-03-25 15:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_idurlmercadopago_alter_course_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 25, 15, 25, 44, 957461, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
