# Generated by Django 2.0.2 on 2024-02-18 22:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_idurlmercadopago_alter_course_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 22, 21, 40, 154494, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
