# Generated by Django 2.0.2 on 2020-08-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tagsNews',
            field=models.ManyToManyField(related_name='get_tags', to='news.TagNews', verbose_name='Tags'),
        ),
    ]
